### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by jdev082**
An initial implementation of sandboxed plugins that utilize the new plugin APIs.

### CODE REVIEW

**Comment by ninjamar** [comment]
This allows arbitrary code execution...

**Comment by jdev082** [comment]
> This allows arbitrary code execution...

As far as I'm aware the ONLY way to implement plugins securely is the method in use with blocked keywords.

**Comment by ninjamar** [comment]
> > This allows arbitrary code execution...
> 
> As far as I'm aware the ONLY way to implement plugins securely is the method in use with blocked keywords.

There are so many ways to break the sandbox. 
`(new Function('return this'))()['a' + 'l' + 'e' + 'r' + 't']("This is unsafe")`


There is a tool called [Inappropriate Word] that can create JavaScript using only certain characters.

**Comment by jdev082** [comment]
> There is a tool called [Inappropriate Word] that can create JavaScript using only certain characters.

Is there any way to solve all this?

**Comment by ninjamar** [comment]
> > There is a tool called [Inappropriate Word] that can create JavaScript using only certain characters.
> 
> Is there any way to solve all this?

https://google.com/search?q=electron+webview+plugin+framework

**Comment by jdev082** [comment]
> https://google.com/search?q=electron+webview+plugin+framework

[This?](https://github.com/dutchigor/pluggable-electron).

**Comment by jdev082** [comment]
Plugins will not be making it into the v3.8.0 release

**Comment by dumorando** [comment]
maybe try iframe based sandboxing? a good implementation is in penguinmod's vm https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/util/sandboxed-javascript-runner.js

**Comment by jdev082** [comment]
> maybe try iframe based sandboxing? a good implementation is in penguinmod's vm https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/util/sandboxed-javascript-runner.js

This implementation already uses iframe sandboxing

**Comment by jdev082** [comment]
This code will be reused for this proposal:
https://github.com/orgs/CatalystDevOrg/discussions/505

**Pull request closed without merging**
