### PR TITLE
Switch to Bootstrap Icons.

### PR DESCRIPTION
**Pull request by webdev03**
Please review this first BEFORE MERGING.
Screen Shot 2021-12-25 at 11 22 31 AM

### CODE REVIEW

**Comment by webdev03** [comment]
Check it out, we just removed 8835 lines.

**Comment by webdev03** [comment]
**Please review this first BEFORE MERGING.**

**Comment by JaydenDev** [comment]
im testing it rn

**Comment by JaydenDev** [comment]
it works, is it in the repository itself so its included in builds

**Comment by JaydenDev** [comment]
also if its linked in the HTML it will also work fine

**Comment by webdev03** [comment]
It is in the repository itself, yes.

**Comment by JaydenDev** [comment]
they are good, they take less space. Good for when we have to cut the action bar size in half to add bookmarks.

**Comment by webdev03** [comment]
We can even set `width` and `height` on the `img` tag :smile:

**Pull request merged**
