### PR TITLE
fix: remove unnecessary context menu

### PR DESCRIPTION
**Pull request by webdev03**
I was working on a context menu earlier and then decided not to use it. Forgot to remove the HTML.

### CODE REVIEW

**Comment by JaydenDev** [comment]
Feature removal? Why

**Comment by webdev03** [comment]
It was hidden and doesn't have anything for it.

**Comment by webdev03** [comment]
I didn't implement the JS for it.

**Comment by webdev03** [comment]
We already have it so when you go to that page you can unbookmark it too.

**Comment by webdev03** [comment]
I accidentally added something in the flex. Removing...

**Pull request merged**
