### PR TITLE
Add tailwind CSS and live reloading

### PR DESCRIPTION
**Pull request by webdev03**
This adds live reloading with `electron-reloader` for a better development experience so now working with Tailwind actually makes sense, because if you didn't have live reloading, you would have to kill the electron process again and again. It also works with the normal builds, as I wrapped it in a try catch block, because `electron-reloader` is a Dev Dependency. Tell me if you want it to be removed.
I haven't changed other styles to tailwind, though, tell me if I should.

You should also credit MystPi for helping with implementation!

I'd also like to add that instead of running `npm run start` run `npm run dev` if you want to work with Tailwind at the same time.

### CODE REVIEW

**Comment by webdev03** [comment]
Sorry, my editor messed up the formatting, that's why I wanted prettier in the old freecat, but since you say it broke Freecat, I didn't add it.

**Comment by hello-smile6** [comment]
> Sorry, my editor messed up the formatting, that's why I wanted prettier in the old freecat, but since you say it broke Freecat, I didn't add it.

I have an opinion on that, but don't want to offend anyone, so won't say it.

**Comment by hello-smile6** [comment]
```
This adds live reloading with `electron-reloader` for a better development experience so now working with Tailwind actually makes sense, because if you didn't have live reloading, you would have to kill the electron process again and again. It also works with the normal builds, as I wrapped it in a try catch block, because `electron-reloader` is a Dev Dependency. Tell me if you want it to be removed. I haven't changed other styles to tailwind, though, tell me if I should.

Fixes #15 

You should also credit MystPi for helping with implementation!
```
Suggested edits. That way, the issue will auto-close.

**Comment by webdev03** [comment]
Thank you so much for merging! Should I work on the other styles now?

**Comment by hello-smile6** [comment]
> Thank you so much for merging! Should I work on the other styles now?

Could you work on <a href="https://github.com/SpellCheckJS">SpellCheckJS</a> instead?

**Comment by webdev03** [comment]
Why? This is the Catalyst repository.

**Comment by hello-smile6** [comment]
> Why? This is the Catalyst repository.

Because I need help with it!

**Pull request merged**
