### PR TITLE
Hide Menu Bar, Bump NPM Packaging

### PR DESCRIPTION
**Pull request by VelocityDesign**
The title says it all.
Tested it, and it seems to work.
If you have any questions, just let me know :)

### CODE REVIEW

**Comment by VelocityDesign** [comment]
@JaydenDev Take a look at this.

**Comment by JaydenDev** [comment]
so what exactly is bump npm packaging.

**Comment by VelocityDesign** [comment]
I don't know, it said that the package-lock.json was made with an old version and it resolved that.

**Comment by VelocityDesign** [comment]
I could .gitignore that and remake the pull if you would like.

**Comment by JaydenDev** [comment]
oh its all good, merging btw I got font awesome icons working and replacd the text on the buttons to the font awesome icons
and also moved em to the top

**Comment by JaydenDev** [comment]
i forgot to git push my commits before merging, reverting.

**Comment by VelocityDesign** [comment]
Do I need to pull from upstream?

**Pull request merged**
