### PR TITLE
Bookmarks

### LINKED ISSUE #83: Bookmarks
Catalyst Bookmarks
(FYI: No help needed right now, already made #91)

### PR DESCRIPTION
**Pull request by webdev03**
Resolves #83
Screen Shot 2021-12-25 at 9 17 06 PM
The star button adds or removes a page from the bookmarks. I don't know how to store the favicon and load it in later, but if there is a way, I will do it. I was going to store the favicon URL too, but then you could track whenever someone opens up Catalyst which isn't cool (basically, you have some JS, and it sends a signal to the server that they viewed the page, and when you fetch the favicon, if the JS doesn't run and the user agent contains Catalyst, then that is tracking!!)

### CODE REVIEW

**Comment by webdev03** [comment]
I hope you enjoy, I've worked for quite a while.

**Comment by webdev03** [comment]
I was trying to add favicons in the bookmarks, but I heard they can be a big memory leak, and also because it didn't work.

**Comment by webdev03** [comment]
There's also a slight issue, if a title gets too long, then it can be wrapped to a new line. I'm unsure how to fix this. I'll work on it tomorrow.

**Comment by kccuber-scratch** [comment]
make the bookmarks in a rounded lighter color div

**Comment by webdev03** [comment]
@kccuber-scratch  OK

**Comment by webdev03** [comment]
@JaydenDev I hope you don't mind, I had to add a `settings.json` since VSCode started to give me errors. It will help everyone who wants to contribute with VSCode.

**Comment by webdev03** [comment]
@kccuber-scratch I don't think that looks very nice compared to what is already in the PR. I think I missed something.

**Pull request merged**
