### PR TITLE
Fix #18

### LINKED ISSUE #18: Packaging with Electron-Forge

### PR DESCRIPTION
**Pull request by hello-smile6**
Fixes #18

### CODE REVIEW

**Comment by JaydenDev** [comment]
There is way more you have to add and change for electron-forge to build things...

**Comment by hello-smile6** [comment]
@webdev03 I beat you, you can give up. :) I'm really competitive.

**Comment by hello-smile6** [comment]
> There is way more you have to add and change for electron-forge to build things...

It should work as-is, try it.

**Comment by webdev03** [comment]
i did it

**Comment by webdev03** [comment]
Wait, I think electron-forge start doesn't work. Mine works I think...

**Comment by hello-smile6** [comment]
> Wait, I think electron-forge start doesn't work. Mine works I think...

Try it

**Comment by webdev03** [comment]
It takes longer to start on my device.

**Comment by hello-smile6** [comment]
> It takes longer to start on my device.

But it also works better.

**Comment by hello-smile6** [comment]
It's what ninetails uses.

**Comment by webdev03** [comment]
How does it work better? I'd love to know.

**Comment by JaydenDev** [comment]
> How does it work better? I'd love to know.

thats the thing... it doesn't. although in your PR you might need to sort out some directory structure problems before I merge

**Comment by webdev03** [comment]
Which problems?

**Comment by JaydenDev** [comment]
> Which problems?

1. Electron-Forge doesn't like the three electronJS files being in the same directory as the rest
2. Electron-Forge might not include all the files

**Comment by webdev03** [comment]
Hmm, I will debug. Can you wait?

**Comment by webdev03** [comment]
Okay, it works for me, the build I made, hmm...

**Comment by JaydenDev** [comment]
> Okay, it works for me, the build I made, hmm... Can you try again? Or, you can tell me where I need to move stuff, and I will.

oh it builds... does it run? if yes I'll merge

**Comment by webdev03** [comment]
Mine, it runs on my device. **And this is @hello-smile6 pr, NOT mine. I haven't tested this one.**

**Comment by JaydenDev** [comment]
> Mine, it runs on my device. **And this is @hello-smile6 pr, NOT mine. I haven't tested this one.**

merging now.. yours not his

**Comment by hello-smile6** [comment]
> Mine, it runs on my device. **And this is @hello-smile6 pr, NOT mine. I haven't tested this one.**

TEST MINE!!!

**Comment by JaydenDev** [comment]
> > Mine, it runs on my device. **And this is @hello-smile6 pr, NOT mine. I haven't tested this one.**
> 
> TEST MINE!!!

what your PR has done was already done and better. sorry try again next time!

**Comment by webdev03** [comment]
Oh, you can revert mine, if @hello-smile6 is better.

**Comment by hello-smile6** [comment]
> Oh, you can revert mine, if @hello-smile6 is better.

Yes!!!

**Comment by hello-smile6** [comment]
#21

**Comment by webdev03** [comment]
> > Oh, you can revert mine, if @hello-smile6 is better.
> 
> Yes!!!

Please explain why? Also I misunderstood @JaydenDev post https://github.com/JaydenDev/Catalyst/pull/19#issuecomment-997510428 but I think he says mine is better.

**Comment by hello-smile6** [comment]
> > > Oh, you can revert mine, if @hello-smile6 is better.
> > 
> > 
> > Yes!!!
> 
> Please explain why? Also I misunderstood @JaydenDev post [#19 (comment)](https://github.com/JaydenDev/Catalyst/pull/19#issuecomment-997510428) but I think he says mine is better.

You said yours was better.

**Pull request closed without merging**
