### PR TITLE
Apple silicon

### PR DESCRIPTION
**Pull request by webdev03**
I don't think I'll contribute for any longer. But here's my last one. I realised that you can build for Apple Silicon on Intel, somehow. So I did it.

### CODE REVIEW

**Comment by webdev03** [comment]
You can run the same thing on Windows too

**Comment by webdev03** [comment]
Bye

**Comment by JaydenDev** [comment]
Doesn't at all work. In fact it makes all the other builds fail.

**Comment by webdev03** [comment]
#140

**Pull request merged**
