### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by webdev03**

### CODE REVIEW

**Comment by JaydenDev** [comment]
explain your PR please

**Comment by webdev03** [comment]
OK, it adds the `publish` script.

**Comment by JaydenDev** [comment]
> OK, it adds the `publish` script. The final piece of the puzzle of creating automatic releases. I needed to do this in a separate PR. Please review and merge :D

you are making making releases complicated, now I can't do it.

**Comment by webdev03** [comment]
Sorry!!!

**Comment by JaydenDev** [comment]
i think its working its building i think, for some reason its making ME build it

**Comment by JaydenDev** [comment]
when I cant make win64 win32 or Mac32 or Mac64 binaries

so the whole point of not having to rely on other people to contribute builds is not fulfilled

**Comment by webdev03** [comment]
Haven't added the tag?

**Pull request merged**
