### PR TITLE
Better Tabs

### LINKED ISSUE #30: Tabs, part two.
You said you wanted to continue your work on tabs, so I made this.

### LINKED ISSUE #31: Searching in the search bar.
You shouldn't need to copy any more Ninetails code, so please try not to.

Its as simple as,

if no https:// or http://
then search
duck duck go

right...?

### PR DESCRIPTION
**Pull request by webdev03**
Resolves #30 
Resolves #31

### CODE REVIEW

**Comment by JaydenDev** [comment]
let me know when its finished

**Comment by webdev03** [comment]
K! What else to add?

**Comment by webdev03** [comment]
And also, where is Catalyst logo VelocityDesign made?

**Comment by JaydenDev** [comment]
I'm having trouble finding it
@VelocityDesign 
Where's the logo, I lost it.

**Comment by JaydenDev** [comment]
@webdev03 you can also implement search in search bar in this PR. make sure to add BOTH https and http support

**Comment by webdev03** [comment]
Okay, I will implement that...

**Comment by webdev03** [comment]
Can I change the search bar logic in a new file?

**Comment by JaydenDev** [comment]
Sure you can split files @webdev03

**Comment by webdev03** [comment]
Thanks!

**Comment by JaydenDev** [comment]
the more files, the more promising a browser looks than it actually is.
yes

**Comment by webdev03** [comment]
LOL

**Comment by JaydenDev** [comment]
Can you also hide all the scroll bars int he webview, it makes it look cleaner.

**Comment by webdev03** [comment]
Why?

**Comment by webdev03** [comment]
Some pages have scrolling, do you mean `overflow: auto;`?

**Comment by JaydenDev** [comment]
idk

**Comment by webdev03** [comment]
I'm working on autocompletion! :D

**Comment by webdev03** [comment]
It's going well, just need to get the UI set and working, and we're done! 🎉

**Comment by webdev03** [comment]
I also am going to add inbuilt "popup blocking" 🤣

**Comment by JaydenDev** [comment]
> I also am going to add inbuilt "popup blocking" 🤣

that will break lots of websites, dont.

**Comment by JaydenDev** [comment]
auto completion, cool thats very conveniant
fresh UI, good

popup blocking, breaks lots of websites

**Comment by webdev03** [comment]
Oh, okay, I'll remove that. It said it was a security risk.

**Comment by webdev03** [comment]
Screen Shot 2021-12-21 at 10 20 55 AM
I'm going to make the autocomplete go in front of the webview but not pull it down.

**Comment by JaydenDev** [comment]
some changes to how the suggestions look and a changing of the tab background are some changes that gotta happen.

**Comment by webdev03** [comment]
OK, can you tell me which changes?

**Comment by JaydenDev** [comment]
> OK, can you tell me which changes?

they just needa to be modernized with some tailwind

**Comment by webdev03** [comment]
Can you try to load roblox.com in the current version of Catalyst? Doesn't work for me.

**Comment by webdev03** [comment]
GTG

**Comment by JaydenDev** [comment]
should i merge..??

**Comment by kccuber-scratch** [comment]
> should i merge..??

you can't because it's a draft

**Comment by webdev03** [comment]
Don't merge yet.

**Comment by webdev03** [comment]
Now working on Favicons.

**Comment by JaydenDev** [comment]
ok

**Comment by webdev03** [comment]
Favicons! Favicons!
Screen Shot 2021-12-21 at 1 47 23 PM

**Comment by webdev03** [comment]
By the way, I rearranged the back and forward buttons, as the earlier position didn't make sense to me.

**Comment by JaydenDev** [comment]
completely finished?

**Comment by JaydenDev** [comment]
well im merging so i hope it is...

**Comment by webdev03** [comment]
Yes.

**Pull request merged**
