### PR TITLE
add electron forge

### LINKED ISSUE #18: Packaging with Electron-Forge

### PR DESCRIPTION
**Pull request by webdev03**
Fixes #18 
Works

### CODE REVIEW

**Comment by JaydenDev** [comment]
which order should I merge the two PRs

**Comment by hello-smile6** [comment]
Closed by https://github.com/JaydenDev/Catalyst/pull/19

**Comment by hello-smile6** [comment]
> which order should I merge the two PRs

Merge mine, then theirs.

**Comment by JaydenDev** [comment]
I feel like this PR will have some issues with directories, the directory structure isn't already compatible with electron-forge

**Comment by webdev03** [comment]
Merge mine...

**Comment by hello-smile6** [comment]
> Merge mine... I tried to build, it works.

Mine?

**Comment by webdev03** [comment]
No, the one by @webdev03 please stop.

**Comment by hello-smile6** [comment]
> No, the one by @hello-smile6 

I agree!!!

**Comment by webdev03** [comment]
Please stop being mean...

**Comment by hello-smile6** [comment]
> Please stop being mean...

I'm not!

**Comment by webdev03** [comment]
You are trying to edit my words, and I don't like it. Please stop.

**Comment by hello-smile6** [comment]
> You are trying to edit my words, and I don't like it. Please stop.

Not trying to, I actually am.

**Comment by webdev03** [comment]
@JaydenDev which problems?

**Pull request merged**
