### PR TITLE
Add userstyles

### PR DESCRIPTION
**Pull request by webdev03**
Maybe userscripts too?

### CODE REVIEW

**Comment by webdev03** [comment]
Now I'll work on an interface to add and remove userstyles! :smile:

**Comment by JaydenDev** [comment]
so many commits to review, so little time.

**Comment by webdev03** [comment]
Once it's `ready for review` then review it!

**Comment by webdev03** [comment]
I haven't even added functionality yet.

**Comment by webdev03** [comment]
I'll work more on this later.

**Comment by JaydenDev** [comment]
@webdev03 can you explain what the heck all this is.

**Comment by webdev03** [comment]
User style runner work in progress

**Comment by webdev03** [comment]
I'll open this later when I work on it.

**Comment by JaydenDev** [comment]
@webdev03 can you not close it for no reason? just lock the conversation.

**Comment by webdev03** [comment]
I don't want to work on Catalyst right now...

**Comment by JaydenDev** [comment]
> I don't want to work on Catalyst right now...

Ok? Only close resolved/denied or merged PRs. It's MY repository. Stop being annoying about it, please

**Comment by webdev03** [comment]
Well, I don't want this to be used, that's why I closed it. I don't want to give you insanely complicated code that even at this point I am starting to get a headache from. Userscripts are hard.. and with Vanilla JS I just don't want to work on that.

**Comment by JaydenDev** [comment]
@webdev03 I have so many notifications and stuff to do really?

**Comment by JaydenDev** [comment]
ya know what? no 2.0 I'm deprecating Catalyst again.

**Comment by webdev03** [comment]
Switch to something that is more manageable. `index.html` has way too much in it now.

**Comment by JaydenDev** [comment]
> Switch to something that is more manageable. `index.html` has way too much in it now.

I won't be managing anything at this point.

**Comment by JaydenDev** [comment]
@webdev03 it is neccesary that this feature be added. Please continue to write it.

**Pull request closed without merging**
