### PR TITLE
Design Changes, 2021.1.7

### PR DESCRIPTION
**Pull request by JaydenDev**

### CODE REVIEW

**Comment by kccuber-scratch** [comment]
it's supposed to be 2022.1.7 not 2021.1.7

**Comment by JaydenDev** [comment]
> it's supposed to be 2022.1.7 not 2021.1.7

thats not important

**Comment by kccuber-scratch** [comment]
> > it's supposed to be 2022.1.7 not 2021.1.7
> 
> thats not important

so we're just going to ignore the fact that you are going backwards?

**Comment by JaydenDev** [comment]
> > > it's supposed to be 2022.1.7 not 2021.1.7
> > 
> > 
> > thats not important
> 
> so we're just going to ignore the fact that you are going backwards?

yes

**Comment by JaydenDev** [comment]
Due to issues this PR will be discarded.

**Pull request closed without merging**
