### PR TITLE
rounded corners on navbar and rearrangement

### PR DESCRIPTION
**Pull request by webdev03**

### CODE REVIEW

**Comment by JaydenDev** [comment]
rounded corners make the buttons look funny tho

**Comment by webdev03** [comment]
You sure? Let me see.

**Comment by webdev03** [comment]
Try it again, with my PR it works.

**Comment by JaydenDev** [comment]
The PR didnt change a thing for me

**Comment by JaydenDev** [comment]
oh it did the last button is rounded

**Comment by JaydenDev** [comment]
wdym rearrange

**Comment by JaydenDev** [comment]
oh i see u fixed the arrow buttons

**Comment by JaydenDev** [comment]
so how will tabs be done?

**Comment by webdev03** [comment]
I will show you later

**Comment by JaydenDev** [comment]
k

**Pull request merged**
