### PR TITLE
Show version in settings.

### PR DESCRIPTION
**Pull request by JaydenDev**
Creation of PR.
Starting Commits.

### CODE REVIEW

**Comment by webdev03** [comment]
Ok should I review?

**Review by webdev03 — CHANGES_REQUESTED** [review]
I suggest styling the button, and also, function isn't a descriptive function name.

**Comment by JaydenDev** [comment]
I got version in preferences handled.

**Comment by JaydenDev** [comment]
> I suggest styling the button, and also, function isn't a descriptive function name.

That's starting code to get my idea out there.

**Comment by JaydenDev** [comment]
@webdev03 can't i use {{version}} in HTML?
image

**Comment by JaydenDev** [comment]
issues:
button too big
all the other buttons went away (solution, less spacing/br tags.)

**Comment by webdev03** [comment]
Just use JS to update it. Or you can use Svelte.

**Comment by JaydenDev** [comment]
> Just use JS to update it. Or you can use Svelte. @hello-smile6 wants you to use MystPi's BridgeJS though. I think it is too much for this purpose.

could you work on putting the version information in the settings panel while I fix sizing and completely discard the button to check for updates button as its a pain to implement and useless.

**Comment by webdev03** [comment]
If we work at the same time on the same branch, I can only imagine conflicts.

**Comment by webdev03** [comment]
I'll add it, but promise not to push another commit while I'm working?

**Comment by JaydenDev** [comment]
> I'll add it, but promise not to push another commit while I'm working?

ive pushed all the commits i need to.

**Comment by JaydenDev** [comment]
make sure to push to the right branch. not master. jd-something-1, to add to this PR.

**Comment by JaydenDev** [comment]
@webdev03 I've removed the check for updates button cuz its useless, make sure to not re-add it.

**Comment by webdev03** [comment]
OK...

**Comment by JaydenDev** [comment]
have you found a method?

**Comment by webdev03** [comment]
So you want a version thing? Can't you already go in the menu bar and then about catalyst?

**Comment by webdev03** [comment]
I was trying to use a context bridge to pass data but it kept on giving errors so I undoed my change.

**Comment by JaydenDev** [comment]
> So you want a version thing? Can't you already go in the menu bar and then about catalyst?

thats to set user agent not any version thi- oh wait. hold on

**Comment by JaydenDev** [comment]
> > So you want a version thing? Can't you already go in the menu bar and then about catalyst?
> 
> thats to set user agent not any version thi- oh wait. hold on

nope the help button in the menu bar doesn't even work.

**Comment by webdev03** [comment]
Ok, let me try

**Comment by JaydenDev** [comment]
> Ok, let me try OK, so I'll make it work.

A custom popup for the help  > about catalyst is also apparently possible. But since all browsers show the version in the settings panel, why not here?

**Comment by webdev03** [comment]
I'm working on it.

**Comment by JaydenDev** [comment]
once this PR is finished I'll be releasing 1.1.1

**Comment by webdev03** [comment]
Done!

**Review by webdev03 — APPROVED** [review]

**Comment by JaydenDev** [comment]
im testing the PR now.

**Comment by JaydenDev** [comment]
works!

**Pull request merged**
