### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by hello-smile6** [comment]
@VelocityDesign Does it work for you?

**Comment by JaydenDev** [comment]
This better work or im gonna stop accepting your PRs.

**Comment by JaydenDev** [comment]
your lucky, it worked

**Comment by hello-smile6** [comment]
> This better work or im gonna stop accepting your PRs.

Of course it works!!!

**Comment by JaydenDev** [comment]
@hello-smile6 have your PRs haven't...

**Comment by webdev03** [comment]
Hey, @hello-smile6 did you SECRETLY change `npm run start`?

**Comment by JaydenDev** [comment]
> Hey, @hello-smile6 did you SECRETLY change `npm run start`? Why, your commit name is misleading...

i changed it back
@hello-smile6 last straw

**Comment by hello-smile6** [comment]
> > Hey, @hello-smile6 did you SECRETLY change `npm run start`? Why, your commit name is misleading...
> 
> i changed it back @hello-smile6 last straw

Sorry!!!

**Comment by hello-smile6** [comment]
@JaydenDev I'll make a workflow that'll fail if `electron-forge start` is found anywhere in package.json, okay? Sorry. Making another PR to fix the start command.

**Comment by JaydenDev** [comment]
> @JaydenDev I'll make a workflow that'll fail if `electron-forge start` is found anywhere in package.json, okay? Sorry. Making another PR to fix the start command.

ok now your adding repo bloat again.
I already fixed the command
refrain from commenting on closed PRs.

**Comment by hello-smile6** [comment]
> > @JaydenDev I'll make a workflow that'll fail if `electron-forge start` is found anywhere in package.json, okay? Sorry. Making another PR to fix the start command.
> 
> ok now your adding repo bloat again. I already fixed the command refrain from commenting on closed PRs.

I was just trying to help!

**Review by webdev03 — COMMENTED** [review]
why

**Pull request merged**
