### PR TITLE
add auto building

### PR DESCRIPTION
**Pull request by webdev03**
This is a bit different from the ninetails system.
What you first do, is create a tag that starts with v, like this from https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd where I got this system from:
image
Then, a draft PR should come up in your releases. Edit the description and stuff, then release it!

### CODE REVIEW

**Comment by webdev03** [comment]
You won't make the release yourself, you just make the git tag from the cli/github desktop and push it. Then Electron Forge can handle all the rest, creating the release with binaries. Then you can edit the description and release it :smile:

**Comment by webdev03** [comment]
Thanks!

**Comment by webdev03** [comment]
Can you try it?

**Comment by JaydenDev** [comment]
@webdev03
you cant make a tag without makin a release

**Comment by webdev03** [comment]
You can.

**Comment by webdev03** [comment]
Just run `npm version minor` or whatever `npm version` it automatically adds a tag too.

**Comment by JaydenDev** [comment]
You have to create tags via github

**Comment by JaydenDev** [comment]
and it does not let you

**Comment by webdev03** [comment]
You can use https://user-images.githubusercontent.com/75148774/147155381-9476f789-b01e-47c8-8c1a-534733c9b46b.png

**Comment by JaydenDev** [comment]
npm ERR! Git working directory not clean.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jmwills/.npm/_logs/2021-12-22T21_38_36_194Z-debug.log

**Comment by JaydenDev** [comment]
so yeah no you cant

**Comment by webdev03** [comment]
No, you need to commit your changes :P

**Comment by JaydenDev** [comment]
❯ npm version minor
v21.13.0

**Comment by webdev03** [comment]
I think you might not be following semver?

**Comment by JaydenDev** [comment]
"npm version" shows the version of npm
are you stupid?

**Comment by webdev03** [comment]
Look, can I give you some steps

**Comment by JaydenDev** [comment]
"npm version" shows the version of NPM

**Comment by webdev03** [comment]
`npm version 0.4.0` will work.

**Comment by webdev03** [comment]
https://github.com/webdev03/ninetails/tree/v2.3.0 this tag was made with the CLI.

**Comment by webdev03** [comment]
Hmm, that's weird

**Comment by JaydenDev** [comment]
LMAO
i got it to work but ur GH action is a failure.
dont upload broken PRs.

**Comment by webdev03** [comment]
I made a fix for it. For some reason, while I was typing, my editor broke it. So sorry!! :sob:

**Pull request merged**
