### PR TITLE
Revert "add electron forge"

### PR DESCRIPTION
**Pull request by hello-smile6**
Reverts JaydenDev/Catalyst#20

### CODE REVIEW

**Comment by webdev03** [comment]
But I like an explanation on why...

**Comment by JaydenDev** [comment]
he has no reason, it works just fine..

**Comment by hello-smile6** [comment]
> But I like an explanation on why...

You wanted mine used instead.

**Comment by webdev03** [comment]
No, I had misunderstood JaydenDev's comment, sorry! 😢

**Comment by JaydenDev** [comment]
ok the point isn't to rush out PRs its to ACTUALLY make a USEFUL PR not a half made one
lesson learned @hello-smile6

**Pull request closed without merging**
