### PR TITLE
add build.sh

### PR DESCRIPTION
**Pull request by michaeleldar**
Wiki will also need updating.

Why: Because building takes time that could be used for something else, and typing `npm install && npm run tailwind:once && npm run make` takes too long.

### CODE REVIEW

**Comment by jdev082** [comment]
@michaeleldar I just implemented something similar, now you can just run `npm run build` and it'll build the css then build the application.

**Comment by michaeleldar** [comment]
Does it also run npm install?

**Comment by jdev082** [comment]
> Does it also run npm install?

it uses commands that you have to do npm install to run

**Comment by michaeleldar** [comment]
> > Does it also run npm install?
> 
> it uses commands that you have to do npm install to run

So by running npm install it also runs npm run tailwind:once and npm run make

**Pull request closed without merging**
