### PR TITLE
Tabs

### LINKED ISSUE #23: Tabs
It's what Catalyst is missing... what it needs to be a huge success...
I don't CARE if you take SOME code from Ninetails just credit em.
Use APIs fine idc just fine a cross platform method of TABS :DDD

### PR DESCRIPTION
**Pull request by webdev03**
Resolves #23
Screen Shot 2021-12-20 at 11 10 52 PM
This is a **work in progress** and I am going to sleep soon, tomorrow morning I will work on this more.

### CODE REVIEW

**Comment by webdev03** [comment]
I made it so you can remove tabs now, please check this tonight but don't merge, I need to make the UI better as I am a bit sleepy.

**Comment by webdev03** [comment]
(also what is the colour scheme for Catalyst? I can't seem to find the logo now)

**Comment by webdev03** [comment]
By the way, I needed a page to load on start, so I made a really barebones Welcome page.

**Comment by webdev03** [comment]
I'm going to go now, in the future, make sure that nobody changes the ID names without carefully updating the JS and testing it as the tabs rely on these ID names.

**Comment by webdev03** [comment]
Screen Shot 2021-12-20 at 11 10 52 PM
Favicons will be implemented tomorrow.

**Comment by JaydenDev** [comment]
Oh heck yes this is getting good.

**Comment by webdev03** [comment]
Thank you so much!

**Comment by JaydenDev** [comment]
> Thank you so much!

Once tabs are finished, should I release 1.0 or wait til the originally planned release date of January 1st, 2022.

**Comment by LegoManiac04** [comment]
> > Thank you so much!
> 
> Once tabs are finished, should I release 1.0 or wait til the originally planned release date of January 1st, 2022.

You could always release it as a pre-release/beta, allowing users to try things out and report any bugs/issues before it officially releases on the 1st.

**Comment by JaydenDev** [comment]
@LegoManiac04 The 1st seems a bit far away, I kinda want people to see this kool browser.
Ninetails is a compeititor and they are far ahead

**Comment by JaydenDev** [comment]
ready to merge?

**Comment by JaydenDev** [comment]
@webdev03 you did say it was ready right?

**Comment by webdev03** [comment]
No it was a draft

**Comment by webdev03** [comment]
Please revert it and let me make the req again

**Comment by JaydenDev** [comment]
> Please revert it and let me make the req again

ok, and btw. you brought an old ninetails bug into the browser. Can't log into the scratch website, look at the ninetails repo to fix the bug

**Comment by webdev03** [comment]
Nevermind I'll work on it in another PR I gtg

**Comment by JaydenDev** [comment]
@webdev03 make sure to fix the scratch bug!

**Comment by webdev03** [comment]
Which bug?

**Comment by webdev03** [comment]
Ah, oh well, how did you fix that bug?

**Comment by MystPi** [comment]
It's a little too similar to Ninetails IMO. Could you change it up a bit?

**Comment by webdev03** [comment]
Ok!

**Pull request merged**
